name: Build and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Build the Docker image
    - name: Build
      run: |-
        docker build -t zh-cn-fonts . 

    # Run the Docker image
    - name: Run
      run: |-
        docker run --rm -v /tmp/artifacts:/tmp/artifacts
    
    # Upload the artifact
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        path: /tmp/artifacts/
        retention-days: 30
